### ISSUE TITLE
I could not make it work with grid library only, how would you do that please ?

### ISSUE THREAD

**Issue by GBoGBoGBo** [thomasp85/fawkes#1]
Hello Sir,
Very interesting work here ! I managed to get your ggplot example work perfectly on Rstudio with ghost_dev(), but I just would like to plot simple shapes such as grid.circle(), grid.rect(), grid.line.to(). Could you please add such an example of simple shapes with library(grid) and not library(ggplot2) please ? Thanks a lot !

**Comment by thomasp85** [comment]
There are no differences to the ggplot2 example. You open up the device and call your grid function. Then close the device in the end
